# --- Qdrant & Database Configuration ---
qdrant:
  url: "http://localhost:6333"
  collection_name: "final4"


# --- Graph Structure & Node Initialization ---
graph:
  total_nodes: 500
  input_nodes: 14
  output_nodes: 10
  cardinality: 5
  radiation_targets: 5

# --- Model Architecture ---
model:
  vector_dim: 56
  phase_bins: 256
  mag_bins: 256
  gamma: 1.0
  iterations: 5
  activation_threshold: 0.05

# --- Training Hyperparameters ---
training:
  lr: 0.1
  worker_count: 1
  timeout: 300 #time to wait for data from queue


# --- System & Logging ---
system:
  device: "cuda"
  logging:
    log_path: "training_logs/log0.csv"
    save_interval_seconds: 10