qdrant:
  url: http://localhost:6333
  collection_name: run1_733e842c6a92e9a2
graph:
  total_nodes: 500
  input_nodes: 64
  output_nodes: 3
  cardinality: 10
  radiation_targets: 2
model:
  vector_dim: 16
  phase_bins: null
  mag_bins: null
  gamma: 0.1
  iterations: 7
  radiation_similarity_threshold: 0.5
  temporal_decay: 0.5
  activation_threshold: 0.0
training:
  lr: 0.01
  accumulation_steps: 4
  epochs: 10
system:
  device: cuda
  random_seed: 42
  logging:
    log_path: genetic_algorithm_runs\run1\733e842c6a92e9a2\loss.csv
    save_interval_seconds: 10
    fieldnames: loss
    tensorboard_dir: genetic_algorithm_runs\run1\733e842c6a92e9a2\tensorboard
    verbose: false
  weights_save_path: genetic_algorithm_runs\run1\733e842c6a92e9a2\weights.pt
