qdrant:
  url: http://localhost:6333
  collection_name: run1_63fb12c29d06ae82
graph:
  total_nodes: 1000
  input_nodes: 16
  output_nodes: 3
  cardinality: 30
  radiation_targets: 40
model:
  vector_dim: 16
  phase_bins: null
  mag_bins: null
  gamma: 1.0
  iterations: 2
  radiation_similarity_threshold: 0.0
  temporal_decay: 0.99
  activation_threshold: 0.0
training:
  lr: 0.01
  accumulation_steps: 4
  epochs: 5
system:
  device: cuda
  random_seed: 42
  logging:
    log_path: genetic_algorithm_runs/run1/63fb12c29d06ae82/loss.csv
    save_interval_seconds: 10
    fieldnames: iteration
    tensorboard_dir: genetic_algorithm_runs/run1/63fb12c29d06ae82/tensorboard
    verbose: false
  weights_save_path: genetic_algorithm_runs/run1/63fb12c29d06ae82/weights.pt
