qdrant:
  url: http://localhost:6333
  collection_name: run1_ef7371b525ee888b
graph:
  total_nodes: 50
  input_nodes: 16
  output_nodes: 3
  cardinality: 10
  radiation_targets: 10
model:
  vector_dim: 16
  phase_bins: null
  mag_bins: null
  gamma: 1.0
  iterations: 15
  radiation_similarity_threshold: 0.0
  temporal_decay: 0.5
  activation_threshold: 0.0
training:
  lr: 1.0
  accumulation_steps: 8
  epochs: 10
system:
  device: cuda
  random_seed: 42
  logging:
    log_path: genetic_algorithm_runs\run1\ef7371b525ee888b\loss.csv
    save_interval_seconds: 10
    fieldnames: loss
    tensorboard_dir: genetic_algorithm_runs\run1\ef7371b525ee888b\tensorboard
    verbose: false
  weights_save_path: genetic_algorithm_runs\run1\ef7371b525ee888b\weights.pt
