# --- Qdrant & Database Configuration ---
qdrant:
  url: "http://localhost:6333"
  collection_name: "run2"


# --- Graph Structure & Node Initialization ---
graph:
  total_nodes: 30000 #123633664/ (1000 * vector_dim)
  input_nodes: 3136 # 512*7*7 / vector_dim
  output_nodes: 256
  cardinality: 1000 
  radiation_targets: 0

# --- Model Architecture ---
model:
  vector_dim: 8
  # phase_bins: null
  # mag_bins: null
  # gamma: 1.5
  iterations: 5
  radiation_similarity_threshold: 0.1
  temporal_decay: 1.0
  activation_threshold: 0.1
  dtype: "float32"
  scattering_prob: 0.0
  stochastic_radiation_duration: 0.4
  layernorm: false
  dropout: 0.0

# --- Training Hyperparameters ---
training:
  lr: 0.0001
  batch_size: 4
  accumulation_steps: 4
  epochs: 5
  validation_fraction: 0.0


# --- System & Logging ---
system:
  device: "mps"
  random_seed: 42
  weights_save_path: "training_runs/run2/run2_weights.pt"
  logging:
    log_path: "training_runs/run2/run2.csv"
    save_interval_seconds: 10
    fieldnames: ['worker_id', 'loss', 'class', 'skipped']
    tensorboard_dir: null
    verbose: false
